# Jekyll Configuration File

# Site settings made available as site.PARAMETER_NAME variable in every page within the website
title: Woodland Corps
email: contact@fakeemail.com
description: >
  A website for the Woodland Corps, a group of Dungeons and Dragons adventurers.
#baseurl: "" # Base URL for the site (e.g., /woodland-corps)
#url: "https://yourusername.github.io" # Your GitHub Pages URL

# Build settings
theme: minima
# markdown: kramdown
# permalink: pretty

# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - sulu-vapen.md

# # Collections
# collections:
#   characters:
#     output: true
#   blog:
#     output: true

# # Plugins
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# # Defaults
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: default

# # Exclude files from the build
# exclude:
#   - README.md
#   - _layout.md

# # Include additional files
# include:
#   - .htaccess